%%{init: { 'logLevel': 'debug', 'theme': 'base', 'gitGraph': {'showBranches': true, 'showCommitLabel':false,'mainBranchName': 'main'} } }%%
   gitGraph
       commit
       
       branch hotfix
       branch release
       branch develop
       branch feature
       
       checkout feature
       commit
       commit
       
       checkout develop
       merge feature
       
       checkout release
       merge develop
       commit
       
       checkout main
       merge release tag: "v1.0.0"
       
       checkout hotfix
       commit
       
       checkout main
       merge hotfix tag: "v1.0.1"